### ISSUE TITLE
问一下，图片详情的EXIF信息展示和地图展示用的什么模块

### ISSUE THREAD

**Issue by bytepoem** [Darmau/koktohay-next#40]
问一下，图片详情的EXIF信息展示和地图展示用的什么模块

![SCR-20230324-mxoh](https://user-images.githubusercontent.com/48577796/227443458-44f1ac7e-b924-4a44-9e55-6d534776f337.jpeg)

**Comment by darmau** [comment]
exif组件在这：https://github.com/Darmau/koktohay-next/blob/main/components/ExifInfo.tsx
查询接口是自己写了一个：https://github.com/Darmau/fetch-exif

地图组件是https://github.com/Darmau/koktohay-next/blob/main/components/Map.tsx

**Comment by bytepoem** [comment]
谢谢
